"""Generate the VAPID key pair that signs browser push alerts, and store it in .env.

Run once from the repo root:  .venv\\Scripts\\python.exe scripts\\gen_vapid.py
Then push it to the repo with scripts\\push-config.ps1. The private key is ours (not an
account credential); losing it only means readers have to re-enable alerts.
"""
from __future__ import annotations

import base64
import sys
from pathlib import Path

try:
    from py_vapid import Vapid
except ImportError:
    sys.exit("pip install pywebpush first (it brings py_vapid)")

from cryptography.hazmat.primitives import serialization

root = Path(__file__).resolve().parent.parent
env_path = root / ".env"
lines = env_path.read_text(encoding="utf-8").splitlines() if env_path.exists() else []
current = {l.split("=", 1)[0].strip(): l.split("=", 1)[1].strip() for l in lines if "=" in l and not l.strip().startswith("#")}
if current.get("VAPID_PRIVATE_KEY") and current.get("PUBLIC_VAPID_KEY"):
    print("VAPID keys already present in .env; nothing to do.")
    sys.exit(0)

v = Vapid()
v.generate_keys()
priv = v.private_key.private_numbers().private_value.to_bytes(32, "big")
pub = v.public_key.public_bytes(serialization.Encoding.X962, serialization.PublicFormat.UncompressedPoint)
b64 = lambda b: base64.urlsafe_b64encode(b).decode().rstrip("=")  # noqa: E731

lines = [l for l in lines if not l.startswith(("VAPID_PRIVATE_KEY=", "PUBLIC_VAPID_KEY="))]
lines += ["", "# Web Push signing keys (generated by scripts/gen_vapid.py)", f"VAPID_PRIVATE_KEY={b64(priv)}", f"PUBLIC_VAPID_KEY={b64(pub)}"]
env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
print("Wrote VAPID_PRIVATE_KEY and PUBLIC_VAPID_KEY to .env. Next: scripts\\push-config.ps1")
